docker_rh_repo_base_url: 'https://download.docker.com/linux/centos/7/x86_64/stable'
docker_rh_repo_gpgkey: 'https://download.docker.com/linux/centos/gpg'

docker_versioned_pkg:
  'latest': docker-engine
  '1.11': docker-engine-1.11.2-1.el7.centos
  '1.12': docker-engine-1.12.6-1.el7.centos
  '1.13': docker-engine-1.13.1-1.el7.centos
  '17.03': docker-engine-17.03.1.ce-1.el7.centos
  '17.12': docker-ce-17.12.0.ce-1.el7.centos
  'stable': docker-engine-17.03.1.ce-1.el7.centos
  'edge': docker-engine-17.05.0.ce-1.el7.centos

kubelet_fail_swap_on: false
local_volume_provisioner_base_dir: /mnt/disks

bootstrap_os: centos
docker_storage_options: -s overlay2
docker_version: '17.12'

# Uncomment this if you have more than 3 nameservers, then we'll only use the first 3.
docker_dns_servers_strict: false

helm_version: "v2.8.1"