# -*- mode: ruby -*-
# # vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.gui = false
    vb.linked_clone = true
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__args: ["--verbose", "--archive", "--delete", "-z"]

  vm_name = "node1"
  config.vm.hostname = vm_name
  config.vm.define vm_name
  config.vm.provision "shell", inline: <<-SHELL
     sudo swapoff -a
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "cluster.yml"
    #ansible.inventory_path = "inventory/single/hosts.ini"
    ansible.extra_vars = "@../inventory/single/extravars.yml"
    ansible.verbose = "v"
    ansible.become = true
    ansible.limit = "all"
    ansible.host_key_checking = false
    ansible.groups = {
      "etcd" => [vm_name],
      "kube-master" => [vm_name],
      "kube-node" => [vm_name],
      "k8s-cluster:children" => ["kube-master", "kube-node"],
    }
  end
end
